### ISSUE TITLE
UI to manage optimistic recipient registry requests

### ISSUE THREAD

**Issue by samajammin** [clrfund/clrfund-deployer#50]
Related to https://github.com/clrfund/clrfund-deployer/issues/12 & https://github.com/clrfund/clrfund-deployer/issues/16

Once a CLR.fund instance is deployed, it'd be great to add some "management" features for admins. One in particular would be a screen to manage requests if using the `OptimisticRecipientRegistry` contract.

I'm envisioning a screen of "pending requests" that the registry owner can challenge/execute (via `challengeRequest` & `executeRequest`).

Another nice feature (dependent on https://github.com/clrfund/monorepo/issues/344) would be the ability for owners to approve requests immediately (without having to wait for the `challengePeriodDuration`).

**Comment by samajammin** [comment]
Hey @daodesigner - is this "done"?

I just checked out [your release](https://ipfs.io/ipfs/QmVpDwPHTKssSqJWyyEU1rneQc4ebU94dH9xzABQ6oMzje/) (it looks great!) on the registry admin functionality. I looks like the admin can in fact challenge & execute requests:

![Image 2021-05-03 at 7 58 13 AM](https://user-images.githubusercontent.com/8097623/116893172-84df0180-abe5-11eb-916b-1ce85329aee4.jpg)

I think the functionality I requested in this issue would be a big UX win - to actually fetch the outstanding requests & list them in the app for the admin. That would avoid the need for the admin to input the `_recipientId` - the app could fetch & input this automatically for the user. Otherwise I'm not sure how the admin is supposed to get that data.

Let me know what you think. Thanks!

**Comment by daodesigner** [comment]
need to build the subgraph to index `_recipientId` as the keys for the request mapping aren't tracked on the contract   `mapping(bytes32 => Request) private requests;`. Agree the next thing on bat should be a subgraph to pull in data from contracts in general. Is this the Registry that will be used in production ?

**Comment by samajammin** [comment]
> Is this the Registry that will be used in production

@daodesigner yes we're planning to use the optimistic recipient registry.
